#!/bin/bash

msg=$1

if [ -e ".git/refs/heads/main" ]; then
    branch_name="main"
elif [ -e ".git/refs/heads/master" ]; then
    branch_name="master"
else
    echo "No 'main' or 'master' branch found!"
    exit 1
fi

git checkout $msg

git add .
git commit -m "$msg"
git push origin "$msg"

echo "Changes pushed to $branch_name branch."

