#!/bin/bash


if [ -e ".git/refs/heads/main" ]; then
    branch_name="main"
elif [ -e ".git/refs/heads/master" ]; then
    branch_name="master"
else
    echo "No 'main' or 'master' branch found!"
    exit 1
fi


git switch $branch_name
git pull origin $branch_name
